### ISSUE TITLE
Fetching Error

### ISSUE THREAD

**Issue by korykim** [SimonSelg/egghead-downloader#18]
video:  https://egghead.io/courses/angular-2-dependency-injection-di-explained

error:

The URL is a playlist or series
Found 8 lessons
Fetching lesson pages...
Error: Failed to parse the following lesson pages:***********. They might be for pro subscribers only
Found 2 videos

**Comment by SimonSelg** [comment]
Hey,

this is expected behaviour, as only 2 of the 8 videos in that playlist are accessible for free users.

If that's not the problem you meant, feel free to open this issue again!
