### ISSUE TITLE
Can't start egghead-downloader

### ISSUE THREAD

**Issue by abdoutelb** [SimonSelg/egghead-downloader#20]
When i type egghead-downloader after install i got
`const [, CSRFToken] = pattern.exec(body) || [];`
The error 

> SyntaxError: Unexpected token [

What did i missing ?
the npm version 4.2.0

**Comment by vsharma2266** [comment]
@abdoutelb 
node >= v.6.0.0

**Comment by abdoutelb** [comment]
@vsharma2266 My bad :(, Thanks a lot
