### ISSUE TITLE
Error: failed to parse the lesson page

### ISSUE THREAD

**Issue by codeepic** [SimonSelg/egghead-downloader#5]
I get this error when trying to parse pro videos (I have a pro subscription).

**Comment by SimonSelg** [comment]
That makes sense, as this tool is only meant for free videos (I don't have a pro account, so i was unable to implement parsing of prop videos). But don't prop videos have a download option anyways?

**Comment by codeepic** [comment]
The pro videos have a download option, but you need to download them one by one. I was trying to save myself some time with your tool. If you don't support downloading pro videos, I will have to download them the old way.
