### ISSUE TITLE
Error: unsupported url!

### ISSUE THREAD

**Issue by codeepic** [SimonSelg/egghead-downloader#6]
I get this error when passing a link to egghead-downloader: 'https://egghead.io/courses/rxjs-beyond-the-basics-creating-observables-from-scratch'

**Comment by eespaillat** [comment]
Ran the github code directly and it worked. It was fixed in the latest pull request. However the npm package hasn't been updated with the latest release.

**Comment by SimonSelg** [comment]
Oh, my bad! I'll update the npm package now. Sorry.

**Comment by SimonSelg** [comment]
Done. Thanks for reporting this. And sorry @codeepic  for not replying sooner - I've been too busy...

**Comment by codeepic** [comment]
That's ok, I am guilty of it myself on occasions. Thanks for the fix!
