### ISSUE TITLE
Errors when editing the code and running npm run build or npm run clean

### ISSUE THREAD

**Issue by codeepic** [SimonSelg/egghead-downloader#7]
When running npm run build, the following error appears:
Failed at the egghead-downloader@0.1.7 build script 'rimraf dist && mkdir && babel src'
'rimraf dist' fails
When running npm run clean, the following error appears:
Failed at the egghead-downloader@0.1.7 clean script 'rimraf dist'
'rimraf dist' fails

**Comment by codeepic** [comment]
My node version is 6.2.0

**Comment by SimonSelg** [comment]
Could you provide the full error log please? Thanks :)

**Comment by SimonSelg** [comment]
Closing as OP is not responding. If you're still having problems feel free to open another issue.
