### ISSUE TITLE
Question: Pro Authentication

### ISSUE THREAD

**Issue by nodu** [SimonSelg/egghead-downloader#8]
Hey!  This looks like a great project.

Do you all support authentication for downloading pro videos?  I can't seem to find it listed if so.

Cheers!

**Comment by SimonSelg** [comment]
Hey :) Sorry for the late reply, I've been to busy...

I don't support pro authentication currently, as I don't have a pro account and therefore I'm unable to add it. But if you'd be willing to help with your pro account, I could implement that. 

Cheers,
Simon

**Comment by jremmen** [comment]
If you have a pro account you can use the rss feeds and a downloader like gPodder to easily grab everything you want.

**Comment by titoesteves** [comment]
@jremmen Can you elaborate how to download using gPodder and rss feeds? I have a pro account and would like to try it out.

**Comment by jremmen** [comment]
@titoesteves Install gpodder, add rss feed to gpodder, download. This is off of month old memory but I don't recall there being any surprises.

**Comment by SimonSelg** [comment]
Solved bei #13 !

**Comment by kambojankit** [comment]
Can you please release it to npm repo, i need it urgently. Not able to install using github. 

Your help will be greatly appreciated.

**Comment by SimonSelg** [comment]
Sorry for taking so long to do this. Done.
